# spring
spring:


  # Be sure to also change "mybatis.mapper-locations" when switching between Oracle and Postgresql datasources
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
    auto-commit: false
    maximum-pool-size: ${DB_MAX_ACTIVE_CONN:4}

  #  datasource:
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:mem:mybatis
  #    schema: classpath:init.sql
  #    data: classpath:data.sql
  # MQ

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: admin1234
    virtusal-host: /
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        prefetch: 5
    cache:
      channel:
        size: 50
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      enable.auto.commit: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
  tpd:
    topic-name:
      - advice-topic
      - advice-topic2
      - advice-topic3
    message-per-request: 10
  # mail
  mail:
    host: smtp.gmail.com
    port: 10001
    username: eeit124group1@gmail.com
    #    password: ncgcnhmhlqpfksct
    password: eeit124124
    tls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl.trust: smtp.gmail.com
mq:
  defaultExchange: amqpExchange
  queue: queue
  routeKey: queue_key


#h2:
#  console:
#    enabled: true
#  settings:
#    trace: true
#    web-allow-others: true
#    path: /h2-console
#    mode: PostgreSQL


# server
server:
  port: ${SPRING_SERVER_PORT:10001}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
    min-response-size: 2048

# project
project:
  package: com.example.demo

# mybatis
mybatis:
  config-location: classpath:mapper/mybatis-config.xml
  #  mapper-locations: classpath*:mapper/*.xml
  mapper-locations: classpath:mapper/UserMapper.xml
#  type-handlers-package: com.css.cloud.util.typehandlers




